# Generated by Django 3.0.8 on 2020-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('blogpost_id', models.AutoField(primary_key=True, serialize=False)),
                ('head0', models.CharField(default='', max_length=50)),
                ('head1', models.CharField(default='', max_length=50)),
                ('head2', models.CharField(default='', max_length=50)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('chead2', models.CharField(default='', max_length=5000)),
                ('title', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
