# Generated by Django 3.0.8 on 2020-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200724_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_items', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=5000)),
                ('email', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=5000)),
                ('zip_code', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('uupdate_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('query', models.CharField(max_length=50)),
            ],
        ),
    ]
